# Generated by Django 5.1 on 2024-08-26 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('address', models.CharField(max_length=3000)),
                ('price', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('no_of_rooms', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
