# Generated by Django 5.1 on 2024-08-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='properties',
            table='properties',
        ),
    ]
